@echo off
REM ═══════════════════════════════════════════════════════════════
REM  ALFA_CORE v2.0 - Plug & Play Installer (Windows)
REM ═══════════════════════════════════════════════════════════════
echo.
echo  █████╗ ██╗     ███████╗ █████╗      ██████╗ ██████╗ ██████╗ ███████╗
echo ██╔══██╗██║     ██╔════╝██╔══██╗    ██╔════╝██╔═══██╗██╔══██╗██╔════╝
echo ███████║██║     █████╗  ███████║    ██║     ██║   ██║██████╔╝█████╗  
echo ██╔══██║██║     ██╔══╝  ██╔══██║    ██║     ██║   ██║██╔══██╗██╔══╝  
echo ██║  ██║███████╗██║     ██║  ██║    ╚██████╗╚██████╔╝██║  ██║███████╗
echo ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
echo.
echo  Plug ^& Play Installer v2.0
echo  ════════════════════════════════════════════════════════════════════
echo.

REM Check Python
python --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python not found! Install Python 3.11+ first.
    echo         https://www.python.org/downloads/
    pause
    exit /b 1
)

echo [1/5] Python detected...

REM Create virtual environment
if not exist "venv" (
    echo [2/5] Creating virtual environment...
    python -m venv venv
) else (
    echo [2/5] Virtual environment exists...
)

REM Activate venv
echo [3/5] Activating environment...
call venv\Scripts\activate.bat

REM Install dependencies
echo [4/5] Installing dependencies...
pip install --upgrade pip -q
pip install -r requirements.txt -q

REM Create config if not exists
if not exist "config\local.yaml" (
    echo [5/5] Creating default config...
    if not exist "config" mkdir config
    (
        echo # ALFA_CORE Local Configuration
        echo # Generated by installer
        echo.
        echo api:
        echo   host: "127.0.0.1"
        echo   port: 8000
        echo   debug: true
        echo.
        echo ai:
        echo   provider: "ollama"  # ollama, deepseek, openai
        echo   model: "llama3.2"
        echo   endpoint: "http://localhost:11434"
        echo.
        echo security:
        echo   cerber_enabled: true
        echo   watchdog_enabled: true
        echo.
        echo logging:
        echo   level: "INFO"
        echo   file: "logs/alfa_core.log"
    ) > config\local.yaml
) else (
    echo [5/5] Config exists...
)

echo.
echo ════════════════════════════════════════════════════════════════════
echo  INSTALLATION COMPLETE!
echo ════════════════════════════════════════════════════════════════════
echo.
echo  To start ALFA_CORE:
echo.
echo    venv\Scripts\activate
echo    python -m alfa_core
echo.
echo  Or use quick start:
echo    start.bat
echo.
echo ════════════════════════════════════════════════════════════════════
pause
