#!/bin/bash
# ═══════════════════════════════════════════════════════════════
#  ALFA_CORE v2.0 - Plug & Play Installer (Linux/macOS)
# ═══════════════════════════════════════════════════════════════

echo ""
echo " █████╗ ██╗     ███████╗ █████╗      ██████╗ ██████╗ ██████╗ ███████╗"
echo "██╔══██╗██║     ██╔════╝██╔══██╗    ██╔════╝██╔═══██╗██╔══██╗██╔════╝"
echo "███████║██║     █████╗  ███████║    ██║     ██║   ██║██████╔╝█████╗  "
echo "██╔══██║██║     ██╔══╝  ██╔══██║    ██║     ██║   ██║██╔══██╗██╔══╝  "
echo "██║  ██║███████╗██║     ██║  ██║    ╚██████╗╚██████╔╝██║  ██║███████╗"
echo "╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝"
echo ""
echo " Plug & Play Installer v2.0"
echo " ════════════════════════════════════════════════════════════════════"
echo ""

# Check Python
if ! command -v python3 &> /dev/null; then
    echo "[ERROR] Python3 not found! Install Python 3.11+ first."
    exit 1
fi

echo "[1/5] Python detected..."

# Create virtual environment
if [ ! -d "venv" ]; then
    echo "[2/5] Creating virtual environment..."
    python3 -m venv venv
else
    echo "[2/5] Virtual environment exists..."
fi

# Activate
echo "[3/5] Activating environment..."
source venv/bin/activate

# Install deps
echo "[4/5] Installing dependencies..."
pip install --upgrade pip -q
pip install -r requirements.txt -q

# Config
if [ ! -f "config/local.yaml" ]; then
    echo "[5/5] Creating default config..."
    mkdir -p config
    cat > config/local.yaml << 'EOF'
# ALFA_CORE Local Configuration
# Generated by installer

api:
  host: "127.0.0.1"
  port: 8000
  debug: true

ai:
  provider: "ollama"  # ollama, deepseek, openai
  model: "llama3.2"
  endpoint: "http://localhost:11434"

security:
  cerber_enabled: true
  watchdog_enabled: true

logging:
  level: "INFO"
  file: "logs/alfa_core.log"
EOF
else
    echo "[5/5] Config exists..."
fi

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo " INSTALLATION COMPLETE!"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo " To start ALFA_CORE:"
echo ""
echo "   source venv/bin/activate"
echo "   python -m alfa_core"
echo ""
echo " Or use quick start:"
echo "   ./start.sh"
echo ""
echo "════════════════════════════════════════════════════════════════════"
